# Generated by Django 4.1.2 on 2022-10-16 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_address_city_alter_city_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'managed': True, 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True, 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'managed': True, 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'managed': True, 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='filmcategory',
            options={'managed': True, 'verbose_name_plural': 'Film categories'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'managed': True, 'verbose_name_plural': 'Inventories'},
        ),
    ]
