# Generated by Django 4.1.2 on 2022-10-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_address_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
